### ISSUE TITLE
Is it compatible with python 2.7?

### ISSUE THREAD

**Issue by maoyali** [arraiyopensource/kornia#173]
![image](https://user-images.githubusercontent.com/31682925/60414521-fa08d680-9c0a-11e9-948e-9dcc8e1d4b9b.png)
there are some problems happened, but i donn't know how to solve it,who can tell me why?

**Comment by edgarriba** [comment]
@maoyali kornia is compatible only with python >= 3.6.
The main reason is because python 2 is about to be deprecated see: https://pythonclock.org
In addition, python typing syntax from 2 and 3 is quite different.

BTW, what version of kornia are you using ? In theory in last versions, an error should be raised in case of python versions mismatch. Check: https://github.com/arraiyopensource/kornia/blob/master/kornia/__init__.py#L4

**Comment by maoyali** [comment]
I have solved it with python3.6, thank you ~

**Comment by edgarriba** [comment]
perfect. I'm closing this

**Comment by tpet** [comment]
Having an initial fork for Python 2 if anybody is interested, not much tested yet.

https://github.com/tpet/kornia/tree/python2

**Comment by edgarriba** [comment]
cool ! but be aware that pytorch is dropping out support for python2
https://discuss.pytorch.org/t/dropping-python-2-support-on-january-1st-2020/56730

**Comment by RSKothari** [comment]
Any reason for >=3.6 dependency @edgarriba ?

**Comment by edgarriba** [comment]
We are using mypy syntax for python 3 (which is totally different to python 2 syntax) and it requires >= 3.6
