### ISSUE TITLE
[JIT] Image warp and conversion warnings

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#45]
JIT tests throws the following warnings that should be fixed: https://pastebin.com/XQPURJFy

**Comment by Wizaron** [comment]
* We can safely ignore the following warning since we create a constant tensor (`tr_mat`) in each run.

```
/home/jcmaxwell/Documents/torchgeometry-wizaron/torchgeometry/imgwarp.py:21: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
    [0.0, 0.0, 1.0]])  # 1x3x3
```

* I will try to propose a fix for the other warnings. Currently, those assertions are executed when we trace the function and the corresponding results are saved as constants, hence the traced model does not include the assertions.

**Comment by edgarriba** [comment]
@Wizaron closing this since we found a workaround for that by wrapping functions to torch.jit.script before tracing. Other solutions are welcomed since we are looking for solutions to let the user to specify whether to use jited functions.
